name = "jaffna-tourism"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages Assets configurations
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Global KV database — shared across all devices & regions
[[kv_namespaces]]
binding = "TOURISM_KV"
id = "c4066c4baff442fe81ab3fb1263a6347"
